// Send Email via Resend — Final node in Report Generator workflow
// Mode: runOnceForAllItems
// Sends email with xlsx attachment via Resend API, PATCHes report_emailed_at.

const input = $input.first().json;
const { run_id, metro, triggered_by, report_url, filename, base64, summary } = input;

// Skip if no recipient
if (!triggered_by || triggered_by === 'unknown' || !triggered_by.includes('@')) {
  console.log(`Send Email: skipping — triggered_by is '${triggered_by}' (not a valid email)`);
  return [{ json: { step: 'send_email', skipped: true, reason: 'no_valid_recipient', run_id } }];
}

// Skip if no report data
if (!base64 || !filename) {
  console.log('Send Email: skipping — no report data (base64 or filename missing)');
  return [{ json: { step: 'send_email', skipped: true, reason: 'no_report_data', run_id } }];
}

const resendApiKey = $env.RESEND_API_KEY;
if (!resendApiKey) {
  console.log('Send Email: skipping — RESEND_API_KEY not set');
  return [{ json: { step: 'send_email', skipped: true, reason: 'no_resend_key', run_id } }];
}

// Build email HTML body
const s = summary || {};
const htmlBody = `
<div style="font-family: Arial, sans-serif; max-width: 600px;">
  <h2 style="color: #2F5496;">Pipeline Report Ready</h2>
  <p>Your pipeline run for <strong>${metro}</strong> has completed and the lead report is attached.</p>

  <table style="border-collapse: collapse; margin: 16px 0;">
    <tr><td style="padding: 4px 12px; color: #666;">Total Records</td><td style="padding: 4px 12px; font-weight: bold;">${s.total_records || '-'}</td></tr>
    <tr><td style="padding: 4px 12px; color: #666;">Sendable Leads</td><td style="padding: 4px 12px; font-weight: bold;">${s.sendable || '-'}</td></tr>
    <tr style="background: #f0fff0;"><td style="padding: 4px 12px; color: #666;">Tier 1a (Name+Email+Phone)</td><td style="padding: 4px 12px; font-weight: bold;">${s.tier_1a || 0}</td></tr>
    <tr style="background: #f0fff0;"><td style="padding: 4px 12px; color: #666;">Tier 1b (Name+Channel)</td><td style="padding: 4px 12px; font-weight: bold;">${s.tier_1b || 0}</td></tr>
    <tr><td style="padding: 4px 12px; color: #666;">Tier 2a (Phone+Website)</td><td style="padding: 4px 12px; font-weight: bold;">${s.tier_2a || 0}</td></tr>
    <tr><td style="padding: 4px 12px; color: #666;">Tier 2b (Cold Call)</td><td style="padding: 4px 12px; font-weight: bold;">${s.tier_2b || 0}</td></tr>
    <tr><td style="padding: 4px 12px; color: #666;">Other (not sendable)</td><td style="padding: 4px 12px; font-weight: bold;">${s.other || 0}</td></tr>
    <tr><td style="padding: 4px 12px; color: #666;">Metros</td><td style="padding: 4px 12px; font-weight: bold;">${s.metros || '-'}</td></tr>
  </table>

  ${report_url ? `<p><a href="${report_url}" style="color: #2F5496;">Download report from dashboard</a></p>` : ''}

  <p style="color: #999; font-size: 12px;">Generated by VerveLabs Pipeline</p>
</div>
`;

try {
  const response = await this.helpers.httpRequest({
    method: 'POST',
    url: 'https://api.resend.com/emails',
    headers: {
      'Authorization': `Bearer ${resendApiKey}`,
      'Content-Type': 'application/json'
    },
    body: {
      from: 'VerveLabs Pipeline <reports@vervelabs.com>',
      to: [triggered_by],
      subject: `Lead Report: ${metro} — ${s.sendable || 0} qualified leads`,
      html: htmlBody,
      attachments: [{
        filename: filename,
        content: base64
      }]
    },
    json: true
  });

  console.log(`Send Email: sent to ${triggered_by} — resend id: ${response.id || 'unknown'}`);

  // PATCH report_emailed_at
  const supabaseUrl = $env.SUPABASE_URL;
  const supabaseKey = $env.SUPABASE_SERVICE_KEY;
  try {
    await this.helpers.httpRequest({
      method: 'PATCH',
      url: `${supabaseUrl}/rest/v1/pipeline_runs?id=eq.${run_id}`,
      headers: {
        'apikey': supabaseKey,
        'Authorization': 'Bearer ' + supabaseKey,
        'Content-Type': 'application/json',
        'Prefer': 'return=minimal'
      },
      body: { report_emailed_at: new Date().toISOString() },
      json: true
    });
  } catch(e) {
    console.log(`Send Email: WARNING — failed to update report_emailed_at: ${e.message}`);
  }

  return [{ json: {
    step: 'send_email',
    success: true,
    run_id,
    recipient: triggered_by,
    resend_id: response.id || null
  }}];

} catch(e) {
  console.log(`Send Email: ERROR — ${e.message}`);
  return [{ json: {
    step: 'send_email',
    success: false,
    run_id,
    error: e.message
  }}];
}
